version: "3.8"
services:
  postgres:
    container_name: postgres
    image: postgres:15-alpine
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    networks:
      - custom
    volumes:
      - postgres:/var/lib/postgresql/data
      - dblogs:/var/lib/postgresql/logs
    expose:
      - ${POSTGRES_PORT}
  hls:
    container_name: hls
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${DATABASE_NAME}"
      NODE_ENV: development
      PORT: ${PORT}
    ports:
      - "${PORT}:${PORT}"
    networks:
      - custom
    command: npm run docker:build
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - /app/node_modules
networks:
  custom:
    driver: bridge
volumes:
  postgres:
  dblogs:
